### ISSUE TITLE
exceptions in ESGF publisher

### ISSUE THREAD

**Issue by alaniwi** [CDAT/cdat_info#17]
Frequently get the following after otherwise successful completion of `esgpublish`. It does not seem to affect operation of the publisher or the return value. Nonetheless, having "harmless" exception appear in the output on a regular basis will make it harder to spot any that really matter, so it is still a problem, so for the time being we are running the publisher with `UVCDAT_ANONYMOUS_LOG=no`.

```
Exception in thread Thread-2 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/local/conda/envs/esgf-pub-20180927/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/local/conda/envs/esgf-pub-20180927/lib/python2.7/threading.py", line 754, in run
  File "/usr/local/conda/envs/esgf-pub-20180927/lib/python2.7/site-packages/cdat_info/cdat_info.py", line 284, in submitPing
  File "/usr/local/conda/envs/esgf-pub-20180927/lib/python2.7/site-packages/cdat_info/cdat_info.py", line 275, in clean_cache
  File "/usr/local/conda/envs/esgf-pub-20180927/lib/python2.7/site-packages/cdat_info/cdat_info.py", line 234, in post_data
  File "/usr/local/conda/envs/esgf-pub-20180927/lib/python2.7/site-packages/requests/api.py", line 112, in post
  File "/usr/local/conda/envs/esgf-pub-20180927/lib/python2.7/site-packages/requests/api.py", line 58, in request
  File "/usr/local/conda/envs/esgf-pub-20180927/lib/python2.7/site-packages/requests/sessions.py", line 403, in __exit__
  File "/usr/local/conda/envs/esgf-pub-20180927/lib/python2.7/site-packages/requests/sessions.py", line 712, in close
  File "/usr/local/conda/envs/esgf-pub-20180927/lib/python2.7/site-packages/requests/adapters.py", line 324, in close
  File "/usr/local/conda/envs/esgf-pub-20180927/lib/python2.7/site-packages/urllib3/poolmanager.py", line 204, in clear
  File "/usr/local/conda/envs/esgf-pub-20180927/lib/python2.7/site-packages/urllib3/_collections.py", line 91, in clear
  File "/usr/local/conda/envs/esgf-pub-20180927/lib/python2.7/threading.py", line 168, in acquire
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
Unhandled exception in thread started by 
sys.excepthook is missing
lost sys.stderr
```

The `lost sys.stderr` error seems to be when python is writing to a pipe which nothing is reading from, and can be reproduced e.g. with `python -c "print 'hello'" | true`

**Comment by doutriaux1** [comment]
@alaniwi which version of `cdat_info` are you running? 
please run:
```
conda info cdat_info
```

I recently fixed a bunch of things in the nightly if you're not running the latest version, do you mind trying:

```
conda upgrade -c cdat/latest/nightly -c conda-forge cdat_info
```

**Comment by alaniwi** [comment]
That `conda info cdat_info` returns without output, but `conda list` tells me 
```
# Name                    Version                   Build  Channel
cdat_info                 8.0                      py27_0    conda-forge
```
Unfortunately there are various reasons why I am unfortunately not able to test at present, partly due to the intermittent nature of fault (it seems to work for a long period with an occasional burst of failures) and partly due to not wanting to ad-hoc package updates in a well-versioned conda environment and unfortunately not time just now to set up a test environment.  Sorry not to help more at this stage.

If at some point you have cause to believe that a fix to the problem is in a tagged release (for example, if you can reproduce it in 8.0 and then compare that against a later tag) then please say, and then next time I have cause to install a new conda environment I can use the latest tagged release and also put `UVCDAT_ANONYMOUS_LOG=yes` in our publisher setup script and then keep an eye on whether the problem recurs or not.

(In any case, we also will have the publisher running unattended for much of the bulk publication for CMIP6, and for that, I would prefer to run without this extra logging to be on the safe side. If you would like some kind of summary statistics relating to that work then please let me know separately what you would like to know, and I'll see later if anything can be extracted.)

**Comment by doutriaux1** [comment]
@alaniwi we're about to release a new tagged version, (couple of weeks at most) but I would like to make sure it's fixed for you in the next tagged version.

**Comment by alaniwi** [comment]
Sorry, for reasons stated it I'm afraid it's not going to be trivial to test just now - I see the problem from time to time but not necessarily when I am trying to test it, even with a repeated loop. (The same just now.) But if you have cause to think that the changes in the latest release would address a problem like this, then I'll bear in mind to give it a try with logging re-enabled after I next have cause to upgrade.

**Comment by doutriaux1** [comment]
@alaniwi yes that sounds good, I'm 99% sure it's fixed in nightly.

**Comment by alaniwi** [comment]
Okay, thanks.
