### ISSUE TITLE
python3 bootstrap

### ISSUE THREAD

**Issue by dnadeau4** [CDAT/cdat_info#8]
When importing genutil with `Python3`  There is something rong with cache file and `utf-8` or `str` in the cache file.

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/software/anaconda3/envs/cdms3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/software/anaconda3/envs/cdms3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/software/anaconda3/envs/cdms3/lib/python3.6/site-packages/cdat_info/cdat_info.py", line 317, in submitPing
    cache_data(data)
  File "/software/anaconda3/envs/cdms3/lib/python3.6/site-packages/cdat_info/cdat_info.py", line 254, in cache_data
    f.write(repr(cache))
  File "/software/anaconda3/envs/cdms3/lib/python3.6/bz2.py", line 245, in write
    compressed = self._compressor.compress(data)
TypeError: a bytes-like object is required, not 'str'
```

**Comment by doutriaux1** [comment]
@dnadeau4 did you use my p3ed cdat_info?

**Comment by dnadeau4** [comment]
Yep,  just cloned it and installed.

**Comment by doutriaux1** [comment]
ok I will work my way to use your genutil and fix this then. Thx!

**Comment by dnadeau4** [comment]
You can try my python3 with gen util and run python -c "import genutil" and it even hangs forever.

**Comment by doutriaux1** [comment]
@dnadeau4 I don't think this is true anymore? Can we close?
